name: GameManager
author: VectorNetworkProject
version: 0.1.0
api: 4.0
main: VectorNetworkProject\GameManager\GameManager

permission:
  vpn.command.getlist:
    default: true
  vnp.game.entry:
    default: true